(source gnu)
(source melpa)

(depends-on "anaconda-mode")
(depends-on "company-anaconda")
(depends-on "conda")
(depends-on "counsel")
(depends-on "ivy")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "mediawiki")
(depends-on "multi-term")
(depends-on "pallet")
(depends-on "pyvenv")
(depends-on "smex")
(depends-on "swiper")
